server:
  port: 8083
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  info:
    java:
      enabled: true

resilience4j.circuitbreaker:
  instances:
    circuitbreaker:
      registerHealthIndicator: true
      sliding-window-size: 6
      minimum-number-of-calls: 3

recommendingAppUrl: "http://localhost:8090/recommended"
